/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day006manyinput;

import java.awt.Button;
import java.awt.Checkbox;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringJoiner;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author phili
 */
public class Day006ManyInput extends javax.swing.JFrame {

    /**
     * Creates new form Day006ManyInput
     */
    public Day006ManyInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpAges = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbBelow18 = new javax.swing.JRadioButton();
        rb1835 = new javax.swing.JRadioButton();
        rb36Up = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbCat = new javax.swing.JCheckBox();
        cbDog = new javax.swing.JCheckBox();
        cbOther = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbContinent = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sliderPrefTemp = new javax.swing.JSlider();
        btRegisterMe = new javax.swing.JButton();
        lbSlideTemp = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Name");

        jLabel2.setText("Age:");

        btnGrpAges.add(rbBelow18);
        rbBelow18.setText("below 18");

        btnGrpAges.add(rb1835);
        rb1835.setSelected(true);
        rb1835.setText("18 - 35");

        btnGrpAges.add(rb36Up);
        rb36Up.setText("36 and up");

        jLabel3.setText("Pets:");

        cbCat.setText("Cat");

        cbDog.setText("Dog");

        cbOther.setText("Other");

        jLabel4.setText("Continent of Residence");

        cbContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Asia", "Europe", "North America", "South America" }));

        jLabel5.setText("Prefered Temp C");

        sliderPrefTemp.setMajorTickSpacing(5);
        sliderPrefTemp.setMaximum(35);
        sliderPrefTemp.setMinimum(5);
        sliderPrefTemp.setMinorTickSpacing(1);
        sliderPrefTemp.setPaintLabels(true);
        sliderPrefTemp.setSnapToTicks(true);
        sliderPrefTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderPrefTempMouseReleased(evt);
            }
        });

        btRegisterMe.setText("Resister me");
        btRegisterMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbBelow18)
                                    .addComponent(cbCat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbDog)
                                            .addComponent(rb1835))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(cbOther))
                                            .addComponent(rb36Up)))
                                    .addComponent(cbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addComponent(tfName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSlideTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(sliderPrefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btRegisterMe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblOutput)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbBelow18)
                    .addComponent(rb1835)
                    .addComponent(rb36Up))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCat)
                    .addComponent(cbDog)
                    .addComponent(cbOther))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lbSlideTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderPrefTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btRegisterMe)
                .addGap(18, 18, 18)
                .addComponent(lblOutput)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterMeActionPerformed
        // TODO add your handling code here:

        //use a StringJoiner to join values from all components to build the dataString
        StringJoiner dataJoiner = new StringJoiner(";");//no space before/after the ";", and use another dilimiter like comma in sub dataStrings like pets
        //get and validate tfname text
        String name = tfName.getText();
        if (name.isEmpty()) {
            lblOutput.setText("Please input your name");
            return;
        }

        dataJoiner.add(name);

        //get  value from the selected radio buttongroup btngrpAges
        ButtonGroup bg = new ButtonGroup();
        bg = btnGrpAges;
        //select the text value of the radio buttons
        JRadioButton rb1 = rbBelow18;
        JRadioButton rb2 = rb1835;
        JRadioButton rb3 = rb36Up;

        rb1.setActionCommand("below 18");
        rb2.setActionCommand("18 - 35");
        rb3.setActionCommand("36 and up");

        String selectedAge = btnGrpAges.getSelection().getActionCommand();

        dataJoiner.add(selectedAge);

        // get text values from all check box pets 
        cbCat.setActionCommand("Cats");
        cbDog.setActionCommand("Dogs");
        cbOther.setActionCommand("Others");

        ArrayList<String> petList = new ArrayList<>();

        if (cbCat.isSelected()) {
            petList.add(cbCat.getActionCommand());
        }

        if (cbDog.isSelected()) {
            petList.add(cbDog.getActionCommand());
        }

        if (cbOther.isSelected()) {
            petList.add(cbOther.getActionCommand());
        }

        StringJoiner sj = new StringJoiner(",");//no space before/after the comma, to avoid error while importing a dataString in the future ;
        for (int i = 0; i < petList.size(); i++) {
            sj.add(petList.get(i));
        }

        String pets = sj.toString();

        dataJoiner.add(pets);

        //get the value from the combobox continent
        int index = cbContinent.getSelectedIndex();
        String continent = cbContinent.getItemAt(index);

        dataJoiner.add(continent);

        //get the value from slider
        int temp = sliderPrefTemp.getValue();
        lbSlideTemp.setText(String.format("%d C", temp));

        dataJoiner.add(String.valueOf(temp));

        //Generate the dataString
        String dataString = dataJoiner.toString();

        //In order to append(not overwrite) dataString to the file, use new PrintWriter(FileOutputStream(new File("dataStrings.txt"))), NOT PrintWriter(new File("dataStrings.txt"));
        try (PrintWriter pw = new PrintWriter(new FileOutputStream(new File("dataStrings.txt"), true)); ) {
           
            pw.println(dataString);
            lblOutput.setText("Data has been saved to the file");

            //reload a new frame
           tfName.setText("");
           

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Failed to append  the data into the file. Error detail:" + e.getMessage(),
                    "Writing Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btRegisterMeActionPerformed

    private void sliderPrefTempMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderPrefTempMouseReleased
        // TODO add your handling code here:
        int temp = sliderPrefTemp.getValue();
        lbSlideTemp.setText(String.format("%d C", temp));
    }//GEN-LAST:event_sliderPrefTempMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day006ManyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day006ManyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day006ManyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day006ManyInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day006ManyInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegisterMe;
    private javax.swing.ButtonGroup btnGrpAges;
    private javax.swing.JCheckBox cbCat;
    private javax.swing.JComboBox<String> cbContinent;
    private javax.swing.JCheckBox cbDog;
    private javax.swing.JCheckBox cbOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbSlideTemp;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JRadioButton rb1835;
    private javax.swing.JRadioButton rb36Up;
    private javax.swing.JRadioButton rbBelow18;
    private javax.swing.JSlider sliderPrefTemp;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
