/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day007tictactoe;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author phili
 */
public class Day007TicTacToe extends javax.swing.JFrame {

    Map<String, String> gameDataMap = new LinkedHashMap<>();
    private int roundNum = 1;
    boolean hasWinner = false;

    private String getCurrentPlayer() {
        if (this.roundNum % 2 == 1) {
            return "O";
        }
        return "X";
    }

    private String matchSameColumn(String columnNum) {

        String winner = "";
        String cuPlayer = gameDataMap.get(0 + columnNum);
        int matchCount = 1;

        for (int i = 0; i < 2; i++) {
            cuPlayer = gameDataMap.get(columnNum + i);
            String nePlayer = gameDataMap.get(columnNum + (i + i));

            if (cuPlayer == null | nePlayer == null) {
                continue;
            } else {
                matchCount += cuPlayer.equals(nePlayer) ? 1 : 0;
            }
        }
        if (matchCount == 3) {
            winner = cuPlayer;
        }

        return winner;
    }

    private String getWinner() {
        //no winner in round 1 -4


            //criteria 1: for any column, its row 0,1,2 have the same player
             for (int i = 0; i < 3; i++) {
                 String player1 = gameDataMap.get(i+"1");
                 String player2 = gameDataMap.get(i+"2");
                 String player3 = gameDataMap.get(i+"3");
                 
                 if (player1 == null || player2 == null || player3 == null ) {
                     break;
                 }else{
                 
                     if (player1.equals(player2)&&player1.equals(player3)) {
                         return player1;
                     }   
                 }     
            }
             
            

            //criteria 2: for any row, its column 0,1,2 have the same player   


            //criteria 3: position 00, 11, 22 have the same player


            //criteria 4: position 22, 11, 00 have the same player


            //if none of above creiteria is met, return empty string "";
            return "";
        
    }

    private void setActionCommands() {
        jButton1.setActionCommand("00");
        jButton2.setActionCommand("01");
        jButton3.setActionCommand("02");
        jButton4.setActionCommand("10");
        jButton5.setActionCommand("11");
        jButton6.setActionCommand("12");
        jButton7.setActionCommand("20");
        jButton8.setActionCommand("21");
        jButton9.setActionCommand("22");
    }

    public Day007TicTacToe() {
        initComponents();
        setActionCommands();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCurrentPlayer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentRound = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        pnMainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Turn of player");

        jLabel2.setText("Turn number");

        btReset.setText("Reset Game");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        pnMainPanel.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton2.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton3.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton3.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton4.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton4.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton5.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton6.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton7.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton7.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton8.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton9.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton9.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClicked(evt);
            }
        });
        pnMainPanel.add(jButton9);

        lblStatus.setText("Welcome to our TicTacToe game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMainPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentPlayer)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentRound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(btReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCurrentPlayer)
                    .addComponent(jLabel2)
                    .addComponent(lblCurrentRound)
                    .addComponent(btReset))
                .addGap(18, 18, 18)
                .addComponent(pnMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClicked
        // TODO add your handling code here:

        //Check if current game is finished, if yes, ask user to reset a new game   
        if (roundNum > 9 || hasWinner == true) {
            lblStatus.setText("This game has finished. Please reset a new one");
            return;
        }

        //get the position of current button
        JButton currentButton = (JButton) evt.getSource();
        String position = currentButton.getActionCommand();

        lblCurrentRound.setText(String.valueOf(roundNum));
        //get current player
        String currentPlayer = getCurrentPlayer();
        lblCurrentPlayer.setText(currentPlayer);

        //verify if current position has been taken
        String player = gameDataMap.get(position);
        if (player == null) {
            //add the position and player to gameDataMap if current button hasn't been taken

            gameDataMap.put(position, currentPlayer);
            currentButton.setText(currentPlayer);

            //check if there's a winner, is yes, strop the game
            String winner = getWinner();

            if (winner.length() > 0) {
                lblStatus.setText("We got a winner: " + winner);
                hasWinner = true;
                return;
            }

            String status = (roundNum == 9) ? "Nice moved, You have finished the game" : ("Nice moved. Next round is round " + (roundNum + 1));
            lblStatus.setText(status);
            roundNum++;
        } else {
            lblStatus.setText("Oh, this position has been taken, please choose another button");
            return;
        }


    }//GEN-LAST:event_btClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Day007TicTacToe().setVisible(true);
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day007TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day007TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day007TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day007TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day007TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCurrentPlayer;
    private javax.swing.JLabel lblCurrentRound;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnMainPanel;
    // End of variables declaration//GEN-END:variables
}
