package day002todos;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author phili
 */
public class Day002Todos {

    static ArrayList<Todo> todoList = new ArrayList<>();
    static Scanner input = new Scanner(System.in);

    //Main menu
    public static void showMenu() {
        System.out.println("\nPlease make a choice [0 - 4]");
        System.out.println("1. Add a todo");
        System.out.println("2. List all todos");
        System.out.println("3. Delete a todo (numbered)");
        System.out.println("4. Modify a todo");
        System.out.println("0. Exit");
        System.out.print("Your choice is: ");
    }

    //1. Add a todo
    public static void addATodo() throws InvalidDataException{
        System.out.println("Adding a todo.");
        
        try {
                //to aviod the empty line (\n) which was generated by previous nextLine command, use one more .nextLine() to consume the empty line
                input.nextLine();
                
                System.out.print("Enter new task description: ");
                String task = input.nextLine();
                
                System.out.print("Enter new due Date (yyyy/mm/dd): ");
                String dueDate = input.nextLine();

                System.out.print("Enter new hours of work (integer): ");
                int hoursOfWork = input.nextInt();
                
                Todo newTodo = new Todo(task,dueDate,hoursOfWork);
                //add the new todo object to the last index of todoList
                todoList.add(newTodo);
                
                
                System.out.printf("You've created the following todo\n");
                System.out.println(todoList.get(todoList.size() - 1).toString());
            } catch (IndexOutOfBoundsException e) {
                throw new InvalidDataException("The todo number does not exist");
            }
    }

    //2. List all todos
    public static void listAllTodos() throws InvalidDataException {
        if (todoList.isEmpty()) {
            throw new InvalidDataException("There are no todos");
        } else {
            for (int i = 0; i < todoList.size(); i++) {
                System.out.printf("#%d: %s", i + 1, todoList.get(i).toString());
            }
        }
    }

    //3. Delete a todo 
    public static void deleteATodo() throws InvalidDataException {
        if (todoList.isEmpty()) {
            throw new InvalidDataException("There are no todos");
        } else {
            System.out.print("Deleting a todo. Which todo# would you like to delete? ");
            try {
                int userInput = input.nextInt();
                todoList.remove(userInput - 1);
                System.out.printf("\nDeleted todo %d successfully.\n", userInput);
            } catch (IndexOutOfBoundsException e) {
                throw new InvalidDataException("The todo number does not exist");
            }
        }
    }

    //4. Modify a todo         
    public static void modifyATodo() throws InvalidDataException {
        if (todoList.isEmpty()) {
            throw new InvalidDataException("There are no todos");
        } else {
            System.out.println("Modifying a todo. Which todo# would you like to modify? ");
            int todoNum = input.nextInt();

            try {
                System.out.print("Enter new task description: ");
                String task = input.nextLine();
                input.next();//use this line to remove the additional data which is created by input.nextLine()  from the ram

                System.out.print("\nEnter new due Date (yyyy/mm/dd): ");
                String dueDate = input.nextLine();
                input.next();

                System.out.print("\nEnter new hours of work (integer): ");
                int hoursOfWork = input.nextInt();

                System.out.print("\nEnter if task is 'Done' or 'Pending': ");
                String status = input.nextLine();
                input.next();

                Todo modfiedToto = new Todo(task, dueDate,hoursOfWork,status);
                todoList.set(todoNum-1, modfiedToto);
                
                System.out.printf("You've modified todo %d as follows:\n", todoNum);
                System.out.println(todoList.get(todoNum - 1).toString());
            } catch (IndexOutOfBoundsException e) {
                throw new InvalidDataException("The todo number does not exist");
            }
        }
    }

    public static void main(String[] args) {

        boolean exitProgram = false;

        while (exitProgram == false) {
            //diesplay the menu
            showMenu();

            try {
                // Validate the user's input
                int userInput = input.nextInt();

                //Call different method basing on userInput
                switch (userInput) {
                    case 0:
                        exitProgram = true;
                        break;
                    case 1:
                        addATodo();
                        break;
                    case 2:
                        listAllTodos();
                        break;
                    case 3:
                        deleteATodo();
                        break;
                    case 4:
                        modifyATodo();
                        break;
                    default:
                        exitProgram = true;
                        break;
                }
            }catch (InvalidDataException e){
                System.out.println(e.getMessage());
            }

        }

        /*
        try {
            Todo td1 = new Todo("Buy , and sell", "2021/02/24", 1);

            System.out.println(td1.toString());
        } catch (InvalidDataException e) {
            System.out.println(e.getMessage());
        }
        */
    }

}
