/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day006helloswing;

import javax.swing.JOptionPane;

/**
 *
 * @author phili
 */
public class Day006HelloSwing extends javax.swing.JFrame {

    /**
     * Creates new form Day006HelloSwing
     */
    public Day006HelloSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btSayHelloViaLabel = new javax.swing.JButton();
        btSayHelloViaMessage = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("What's your name?");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        btSayHelloViaLabel.setText("Say Hello(label)");
        btSayHelloViaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSayHelloViaLabelActionPerformed(evt);
            }
        });

        btSayHelloViaMessage.setText("Say Hello(message box)");
        btSayHelloViaMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSayHelloViaMessageActionPerformed(evt);
            }
        });

        lblGreeting.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGreeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btSayHelloViaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSayHelloViaMessage))
                        .addGap(33, 33, 33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSayHelloViaLabel)
                    .addComponent(btSayHelloViaMessage))
                .addGap(18, 18, 18)
                .addComponent(lblGreeting)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btSayHelloViaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSayHelloViaLabelActionPerformed
        // TODO add your handling code here:
        String name = tfName.getText();
        //validate if the name is null
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Name must not be empty.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
       return;//works like the "break;" key word in a loop. to stop the program to executive the codes after this line.
        }

        String msg = String.format("Hello %s, nice to meet you.", name);

        lblGreeting.setText(msg);

    }//GEN-LAST:event_btSayHelloViaLabelActionPerformed

    private void btSayHelloViaMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSayHelloViaMessageActionPerformed
        // TODO add your handling code here:
 String name = tfName.getText();
        //validate if the name is null
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Name must not be empty.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
            return;//works like the "break;" key word in a loop. to stop the program to executive the codes after this line.
        }

        String msg = String.format("Hello %s, nice to meet you.", name);

        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_btSayHelloViaMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day006HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day006HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day006HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day006HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day006HelloSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSayHelloViaLabel;
    private javax.swing.JButton btSayHelloViaMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
